// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_fTrXW0i_q73r7RbnzU5DsFiVbY5ReEk',
    appId: '1:993071309221:web:b807d1f9f91b9f1bc6084c',
    messagingSenderId: '993071309221',
    projectId: 'amsocialmediaapp',
    authDomain: 'amsocialmediaapp.firebaseapp.com',
    storageBucket: 'amsocialmediaapp.firebasestorage.app',
    measurementId: 'G-XV6P2W195P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPuaNBU5Xb-dFvJZgGeTtys0xBIGSxABE',
    appId: '1:993071309221:android:4273ffcc5f8c9909c6084c',
    messagingSenderId: '993071309221',
    projectId: 'amsocialmediaapp',
    storageBucket: 'amsocialmediaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeL3mVFpmQIeWHtLZl9yueRrprdpaoAW0',
    appId: '1:993071309221:ios:b20d4682cdebb0ddc6084c',
    messagingSenderId: '993071309221',
    projectId: 'amsocialmediaapp',
    storageBucket: 'amsocialmediaapp.firebasestorage.app',
    iosBundleId: 'com.example.amSocialmediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeL3mVFpmQIeWHtLZl9yueRrprdpaoAW0',
    appId: '1:993071309221:ios:b20d4682cdebb0ddc6084c',
    messagingSenderId: '993071309221',
    projectId: 'amsocialmediaapp',
    storageBucket: 'amsocialmediaapp.firebasestorage.app',
    iosBundleId: 'com.example.amSocialmediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_fTrXW0i_q73r7RbnzU5DsFiVbY5ReEk',
    appId: '1:993071309221:web:de36f6029d8b7ea3c6084c',
    messagingSenderId: '993071309221',
    projectId: 'amsocialmediaapp',
    authDomain: 'amsocialmediaapp.firebaseapp.com',
    storageBucket: 'amsocialmediaapp.firebasestorage.app',
    measurementId: 'G-T6D5ZWX2EH',
  );
}
